# Standards: 0.11
---

- include: preflight.yml
  when: cis_apply_level_1_profile or cis_apply_level_2_profile

- include: "level-1/section-1.yml"
  when: cis_apply_level_1_profile and cis_apply_section_1_profile

- include: "level-1/section-2.yml"
  when: cis_apply_level_1_profile and cis_apply_section_2_profile

- include: "level-1/section-3.yml"
  when: cis_apply_level_1_profile and cis_apply_section_3_profile

- include: "level-1/section-4.yml"
  when: cis_apply_level_1_profile and cis_apply_section_4_profile

- include: "level-1/section-5.yml"
  when: cis_apply_level_1_profile and cis_apply_section_3_profile

- include: "level-1/section-6.yml"
  become: yes
  when: cis_apply_level_1_profile and cis_apply_section_6_profile

- include: "level-2.yml"
  become: yes
  when: cis_apply_level_2_profile
